#!/usr/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

sum = 0
f0 = 0
f1 = 1
f = f0 + f1
while f < 4000000:
    if f % 2 == 0:
        sum += f
    f0 = f1
    f1 = f
    f = f0 + f1

print "Answer:", sum
    
