#!/usr/bin/python

# Pentagonal numbers are generated by the formula, Pn = n(3n-1)/2. The first ten
# pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
# 70 - 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
# difference are pentagonal and D = |Pk - Pj| is minimised;
# what is the value of D?


limit = 6000
pentagon = [n * (3 * n - 1) / 2 for n in xrange(1, limit)]
pset = set(pentagon)

for diff in xrange(1, limit / 2):
    left = 0
    right = diff
    while right < limit / 2:
        if ((pentagon[left] + pentagon[right]) in pset
            and (pentagon[right] - pentagon[left]) in pset):
            print pentagon[left], pentagon[right], 'diff:', pentagon[right] - pentagon[left]
            exit(0)
        right += 1
        left += 1
        
