#!/usr/bin/python

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, ...
# Pentagonal Pn=n(3n-1)/2 1, 5, 12, 22, 35, ...
# Hexagonal Hn=n(2n-1) 1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

t = 285
p = 165
h = 143

# t = 1
# p = 1
# h = 1

def T(t):
    return t * (t + 1) / 2
def P(p):
    return p * (3 * p - 1) / 2
def H(h):
    return h * (2 * h - 1)

while h < 1500000:
    h += 1
    HH = H(h)
#     print "H(", h, ") = ", HH
    while P(p) < HH:
        p += 1
#         print "  P(", p, ") = ", P(p)
    PP = P(p)
    if PP == HH:
#         print "found: p:", p, "h:", h, " == ", P(p)
        while T(t) < PP:
            t += 1
#             print "    T(", t, ") = ", T(t)
        if T(t) == PP:
            print "found: t:", t, "p:", p, "h:", h, ", answer:", T(t)
            exit(0)
